version: "2"

linters:
  disable:
    - unused

  settings:
    govet:
      disable:
        - composites
    
    staticcheck:
      checks:
        - all
        - -ST1023

    misspell:
      locale: US
